version: 2.1
orbs:
  node: circleci/node@7

jobs:
  tar:
    parameters:
      use-pigz:
        type: boolean
    executor: node/default
    resource_class: large
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/.npm
      - run: ls -la node_modules
      - when:
          condition: << parameters.use-pigz >>
          steps:
            - run: sudo apt install pigz
      - run:
          time tar <<#parameters.use-pigz>>-I pigz -cvf<</parameters.use-pigz>><<^parameters.use-pigz>>-cvzf<</parameters.use-pigz>> nodemod.tar.gz node_modules

workflows:
  main:
    jobs:
      - tar:
          use-pigz: false
          name: tar-as-usual
      - tar:
          use-pigz: true
          name: tar-with-pigz
